mongodb:
    uri: mongodb+srv://lunahazuki2006:cXU0lYhSncWZ12FM@cluster0.owjghpf.mongodb.net/frutas?retryWrites=true&w=majority&appName=Cluster0
micronaut:
  server:
    cors:
      enabled: true

      configurations:
        ui:
          allowed-origins:
            - http://localhost:8086